# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 23:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=64)),
                ('patronymic', models.CharField(max_length=64, null=True)),
                ('year_born', models.IntegerField(default=1799, validators=[django.core.validators.MaxValueValidator(2015), django.core.validators.MinValueValidator(0)])),
                ('year_death', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveSmallIntegerField(default=0, validators=set([django.core.validators.MaxValueValidator(16), django.core.validators.MinValueValidator(0)]))),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Writing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('release_year', models.IntegerField(default=1873, validators=[django.core.validators.MaxValueValidator(2015), django.core.validators.MinValueValidator(0)])),
                ('page_num', models.PositiveSmallIntegerField()),
                ('description', models.TextField()),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Libry.Language')),
                ('lang_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original', to='Libry.Language')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='writing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Libry.Writing'),
        ),
    ]
