# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 00:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='writing',
            name='author',
            field=models.ManyToManyField(to='Libry.Author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='year_death',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='num',
            field=models.PositiveSmallIntegerField(default=0, validators=set([django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(16)])),
        ),
    ]
