# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 00:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0001_initial'),
        ('Libry', '0003_auto_20151209_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Contact.Country'),
        ),
        migrations.AlterField(
            model_name='book',
            name='num',
            field=models.PositiveSmallIntegerField(default=0, validators=set([django.core.validators.MaxValueValidator(16), django.core.validators.MinValueValidator(0)])),
        ),
    ]
