# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 00:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libry', '0005_auto_20151209_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='num',
            field=models.PositiveSmallIntegerField(default=0, validators=set([django.core.validators.MaxValueValidator(16), django.core.validators.MinValueValidator(0)])),
        ),
    ]
