# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 01:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_user_want2read'),
        ('Libry', '0006_auto_20151209_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_id',
            field=models.ManyToManyField(to='User.User'),
        ),
        migrations.AlterField(
            model_name='book',
            name='num',
            field=models.PositiveSmallIntegerField(default=0, validators=set([django.core.validators.MaxValueValidator(16), django.core.validators.MinValueValidator(0)])),
        ),
    ]
