# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 01:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libry', '0007_auto_20151209_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.ManyToManyField(to='User.User'),
        ),
        migrations.AlterField(
            model_name='book',
            name='num',
            field=models.PositiveSmallIntegerField(default=0, validators=set([django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(16)])),
        ),
    ]
